# Generated by Django 4.2.2 on 2023-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='online',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/default_avatar.png', upload_to='images/avatars/', verbose_name='Фото профілю'),
        ),
    ]
